### ISSUE TITLE
Programming issue ATF1504AS with ATDH1150USB programmer

### ISSUE THREAD

**Issue by pjaegerhh** [SukkoPera/OpenAmiga500FastRamExpansion#10]
Hi there,

when trying to flash ATF1504AS with the ATDH and ATMISP V7.3 sw the sw closes/crashes without any log when starting to flash the ATF1504AS-10JU44. I'm using the "program/verify" mode. Chips are brand new from RS. Flashing ATF1502AS with the V1 firmware works fine.
Any idea what the issue can be ?

**Comment by SukkoPera** [comment]
No idea unfortunately, never used the ATDH nor ATMISP, as I'm no Windows user. Maybe the firmware is just not compatible with the different chip?

I'm leaving this open in the hope someone else can be more useful.

**Comment by pjaegerhh** [comment]
Sometimes software is crazy - downloaded  just the JED from github as single file again, loaded it into ATMISP, and all gucci. No clue what was wrong with the old file out of the zip(which still does not work). 
Sorry for bothering. Issue can be closed.

**Comment by SukkoPera** [comment]
Well, that is definitely odd. Glad you solved it anyway!
