### ISSUE TITLE
TF534 compatibility.

### ISSUE THREAD

**Issue by andreacampanella** [SukkoPera/OpenAmiga500FastRamExpansion#6]
I have been using the card for an year and I recently got a TF534. I can see the memory in Workbench but ram test comes back with some errors.

Is there any known problem with it? 

It's 8MB

**Comment by SukkoPera** [comment]
To be honest, I don't know. I think it is *supposed* to work with the TF534, but I don't have one and can't say for sure.

I'm leaving this open for anyone to contribute.

**Comment by andreacampanella** [comment]
I think my board it's defective, I have to investigate more. 

This is the error but I can't really understand how to interpret it. 
![IMG_20201222_224620](https://user-images.githubusercontent.com/4170190/103105957-5ba3d880-4629-11eb-885b-134db1ac1a05.jpg)

**Comment by SukkoPera** [comment]
I had lot of similar errors while testing mem68k with my TF530. Never managed to fix them.

I'm sorry but I really can't help more :(.

**Comment by andreacampanella** [comment]
Weird, it seems something isolated to the 500+ I'm using, the other 500 it's kinda fine. 

Need more testing, seems harware related.

**Comment by SukkoPera** [comment]
Maybe a wonky socket?

**Comment by andreacampanella** [comment]
I don't really understand, I just removed all the chip ram and I'm about to test it.

**Comment by andreacampanella** [comment]
yeah, something is up with my 500+, works with my 500.

**Comment by SukkoPera** [comment]
OK, closing then.
